# Generated by Django 4.0.4 on 2022-04-23 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_profesor_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='telefono',
        ),
    ]
